FROM python:3.9

WORKDIR /app

COPY /app /app/app

WORKDIR /app/app

RUN pip install -r requirements.txt

ENV GOOGLE_APPLICATION_CREDENTIALS=/app/dynamic-branch-441814-f1-45971c71ec3a.json
# ENV PINECONE_APIKEY=pcsk_3ktCuv_C9DaWcm2i1PKg1je7TSDmxeCE1xV3MKqTNee4GhLJJqQhhUu9QDfJu6P2a99j3A

EXPOSE 30000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "30000"]